version: '3.2' 

volumes:
  postgres-data: {}
  
services:    
     
  keycloak:
    image: jboss/keycloak
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_USER: admin 
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_USER: keycloak
      DB_PASSWORD: p@ssword
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: p@ssword
    volumes:
      - postgres-data:/var/lib/postgresql/data
