server:
  port: 8081
  servlet:
    context-path: /flights/
spring:
  application:
    name: flights-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/spring-cloud-gateway-realm
